combine frontend run with cy step

diff --git a/.github/workflows/cypress.yaml b/.github/workflows/cypress.yaml
--- a/.github/workflows/cypress.yaml
+++ b/.github/workflows/cypress.yaml
@@ -77,18 +77,16 @@ jobs:
           sudo wget -q https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
           sudo apt-get install ./google-chrome-stable_current_amd64.deb
 
-      - name: Start Frontend Application
-        run: npm run build && npm run preview &
-
-      - name: Wait for the Frontend Server to be Ready
-        run: |
-          npx wait-on --timeout 60000 http://localhost:4000 || (  
-            echo "Frontend server failed to start within timeout"  
-            exit 1  
-          )  
+      - name: Build Frontend Application
+        run: npm run build 
 
       - name: Run Cypress Tests in Parallel
         run: |
+          npm run preview &
+          npx wait-on --timeout 60000 http://localhost:4000 || (  
+            echo "Frontend server failed to start within timeout"  
+            exit 1  
+          )
           npm run cy:parallel
 
       -  name: Upload Cypress Screenshots
