improve error handling

diff --git a/.github/workflows/cypress.yaml b/.github/workflows/cypress.yaml
--- a/.github/workflows/cypress.yaml
+++ b/.github/workflows/cypress.yaml
@@ -43,21 +43,28 @@ jobs:
       - name: Start care docker containers 🐳
         run: |
           cd care
+
           echo DISABLE_RATELIMIT=True >> docker/.prebuilt.env
           echo "CORS_ALLOWED_ORIGINS=\"[\\\"http://localhost:4000\\\"]\"" >> docker/.prebuilt.env
           echo JWKS_BASE64=\"$(cat ../.github/runner-files/jwks.b64.txt)\" >> docker/.prebuilt.env
-          docker compose -f docker-compose.yaml -f docker-compose.pre-built.yaml up -d db
+          docker compose up -d db
+          timeout 1m bash -c 'until docker compose exec db pg_isready; do sleep 1; done'
+
           # load the db dump from the artifact if it exists else do the usual
-          set -e
           {
+            set -e
             archive_download_url=$(curl -sf "https://api.github.com/repos/ohcnetwork/care/actions/artifacts?name=care-db-dump" | jq -r '.artifacts[0].archive_download_url')
             curl -Lf -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" -o care-db-dump.zip "$archive_download_url"
             unzip care-db-dump.zip
             make load-db
+            echo "Database loaded successfully."
             make docker_config_file=docker-compose.pre-built.yaml up
           } || {
+            echo "An error occurred during database download and setup."
+            echo "Falling back to loading dummy data."
             make docker_config_file=docker-compose.pre-built.yaml up load-dummy-data
           }
+
           cd ..
 
       - name: Determine PR Origin  
